### ISSUE TITLE
Add kerberos renew function

### ISSUE THREAD

**Issue by jenast** [NINAnor/NinaR#26]
Something like
##Renew kerberos ticket

#Ask for password
passw <- .rs.askForPassword("Enter your Windows password:")

#Kill existing Kerberos tickets
system("/usr/bin/kdestroy", input = passw)

#Initialize Kerberos ticket
system("/usr/bin/kinit", input = passw)

#Delete password string (not sure is needed)
rm(passw)

**Comment by xianwenchen** [comment]
The solution seems reasonable to me.

**Comment by jenast** [comment]
fixed in mountFolders
