### ISSUE TITLE
Update ninsrv16 check for all functions

### ISSUE THREAD

**Issue by jenast** [NINAnor/NinaR#27]
For example, mountFolders() is not updated

**Comment by jenast** [comment]
Actually, this should be replaced by or incorporate the kerberos script.

**Comment by ninsbl** [comment]
Tis can probably be closed....

**Comment by jenast** [comment]
Think this is fixed now. As far as it can be fixed. Perhaps obsolete as well since Rstudio now logs out after x min of inactivity.
