### ISSUE TITLE
NinaR needs a HexSticker :)

### ISSUE THREAD

**Issue by DrMattG** [NINAnor/NinaR#34]
As we discussed a few weeks back: See https://zhuhao.org/post/tips-on-designing-a-hex-sticker-for-rstats-packages/
Using the Library hexSticker (https://github.com/GuangchuangYu/hexSticker) here are some examples I have played with - it needs someone with design experience to make a cool image though.

library(hexSticker)
library(showtext)

#Just using the logo 
imgurl <- "PathToImage"
sticker(imgurl, package="NinaR", 
        p_size=20, # font size
        p_x=1,#horizontal position of text
        p_y=1.6,#vetical position of text
        p_color= "#A2AAAD",
        s_x=1, #horizontal position of image
        s_y=1, #vertical position of image
        s_width=.8,#Width of image
        h_fill="white",
        h_color="#008C95",
        filename="SaveFilename.png")

![NinaHex](https://user-images.githubusercontent.com/11541781/61048224-8ff9e980-a3e1-11e9-9864-c1cdcd29714f.png)

#Using the muskox picture
imgurl2 <- "PathToImage"
sticker(imgurl2, package="NinaR", 
        p_size=18, # font size
        p_x=1,#horizontal position of text
        p_y=1.6,#vetical position of text
        p_color= "#A2AAAD",
        s_x=1, #horizontal position of image
        s_y=.95, #vertical position of image
        s_width=.8,#Width of image
        h_fill="white",
        h_color="#008C95",
        filename="SaveFilename.png")

![MuskOx](https://user-images.githubusercontent.com/11541781/61048251-a0aa5f80-a3e1-11e9-9914-760a730d9d28.png)

#using the red fox picture
imgurl3 <- "PathToImage"
sticker(imgurl3, package="NinaR", 
        p_size=18, # font size
        p_x=1,#horizontal position of text
        p_y=1.6,#vetical position of text
        p_color= "white",
        s_x=1, #horizontal position of image
        s_y=.95, #vertical position of image
        s_width=.7,#Width of image
        h_fill="#A2AAAD",
        h_color="#008C95",
        filename="SaveFilename.png")

![Redfox](https://user-images.githubusercontent.com/11541781/61048300-c59ed280-a3e1-11e9-9bc5-6340d5c0c541.png)

#Load Google fonts (see: http://www.google.com/fonts)
font_add_google("Gochi Hand", "gochi")
font_add_google("Fjalla One", "fjalla")
#showtext to render text for future devices
showtext_auto()

#play with the font
imgurl3 <- "~/My Pictures/rodrev.jpg"
sticker(imgurl3, package="NinaR", 
        p_size=18, # font size
        p_x=1,#horizontal position of text
        p_y=1.6,#vetical position of text
        p_color= "white",
        p_family = "fjalla",
        s_x=1, #horizontal position of image
        s_y=.95, #vertical position of image
        s_width=.7,#Width of image
        h_fill="#A2AAAD",
        h_color="#008C95",
        filename="SaveFilename.png")

![RedfoxFont](https://user-images.githubusercontent.com/11541781/61048183-735db180-a3e1-11e9-959e-8156d3187291.png)

**Comment by jenast** [comment]
I finally got around to this yesterday, but didn't actually see the contents of this issue. So I didn't see your examples @DrMattG .
I'm open to change the sticker later on!

**Comment by DrMattG** [comment]
No worries :)
